# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 14:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 19, 22, 0, 16, 807317)),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
