# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_blog', '0003_auto_20171019_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
