# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('one_blog', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('comment_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-comment_time',),
            },
        ),
    ]
